### ISSUE TITLE
Issues to be closed following next release

### ISSUE THREAD

**Issue by jcfr** [manahl/pytest-plugins#139]
The goal of this issue is to reference the issues that could be closed after the upcoming release:

* [x] #137 Publish new version of pytest-verbose-parametrize to PyPI plz
* [x] #110 Plugins incompatible with pytest 4, leads to ContextualVersionConflict
* [x] #100 Pytest RemovedInPytest4Warning Warning
* [x] #125 Please include wheels for modern Pythons
* [x] #134 pytest-server-fixture: Update RethinkDB fixtures to support rethinkdb >= 2.4.0

**Comment by jcfr** [comment]
Closing. 1.7.0 released :tada: 
See https://github.com/manahl/pytest-plugins/releases/tag/v1.7.0
